### ISSUE TITLE
problem updating to 0.3.0

### ISSUE THREAD

**Issue by chrism** [Vestorly/torii#155]
Hi,

Just tried to update to 0.3.0 from 0.2.2 and am now getting errors when I run `ember serve`

```
⇒  ember serve
version: 0.1.5
Could not find watchman, falling back to NodeWatcher for file system events
Proxying to http://dev.appname.tv:80
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Invalid tree found. You must supply a path or an object with a `read` function.
Error: Invalid tree found. You must supply a path or an object with a `read` function.
    at readAndReturnNodeFor (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:71:13)
    at RSVP.resolve.then.then.finally.readTreeRunning (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:92:24)
    at $$$internal$$tryCatch (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at /Users/username/git/appname-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1096:13
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
^CCleanup error.
Cannot call method 'cleanup' of undefined
TypeError: Cannot call method 'cleanup' of undefined
    at cleanupTree (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:128:19)
    at promise.then.then.results.(anonymous function) (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/broccoli/node_modules/promise-map-series/index.js:8:27)
    at $$$internal$$tryCatch (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/username/git/appname-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

my ember versions

```
version: 0.1.5
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.36
npm: 2.1.8
```

my package.json

```
{
  "name": "appname-app",
  "version": "0.0.0",
  "description": "Small description for appname-app goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-sass": "^0.3.3",
    "ember-cli": "0.1.5",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-esnext": "0.1.1",
    "ember-cli-google-analytics": "^1.3.1",
    "ember-cli-gzip": "^1.1.1",
    "ember-cli-htmlbars": "^0.6.0",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.1.2",
    "ember-cli-simple-auth": "^0.7.2",
    "ember-cli-zero-clipboard": "^1.0.2",
    "ember-data": "1.0.0-beta.12",
    "ember-document-title": "^1.1.7",
    "ember-export-application-global": "^1.0.0",
    "ember-moment": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "liquid-fire": "^0.18.0",
    "torii": "^0.3.0"
  }
}
```

Any ideas what is happening?

Thanks!

**Comment by mixonic** [comment]
@chrism Please upgrade to 0.3.2. Seems like we had some snafus with the new packaging setup.

And feel free to re-open if that doesn't fix things or I've missed something else.

**Comment by chrism** [comment]
yep that fixed it - thanks so much

:+1:
