### ISSUE TITLE
Fire base Crash when Receiving Notification in Android 

### ISSUE THREAD

**Issue by ArunkumarChandraSekar** [Vestorly/torii#310]
java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at com.google.android.gms.measurement.internal.zzw.zza(Unknown Source)
	at com.google.android.gms.measurement.internal.zzw.zzl(Unknown Source)
	at com.google.android.gms.measurement.internal.zzac.zza(Unknown Source)
	at com.google.android.gms.measurement.internal.zzac.zza(Unknown Source)
	at com.google.android.gms.measurement.internal.zzac.zze(Unknown Source)
	at com.google.android.gms.measurement.AppMeasurement.zzd(Unknown Source)
	at com.google.firebase.crash.internal.zza.zzar(Unknown Source)
	at com.google.firebase.crash.internal.zza.zza(Unknown Source)
	at com.google.firebase.crash.FirebaseCrash.zzg(Unknown Source)
	at com.google.firebase.crash.internal.zzh.uncaughtException(Unknown Source)
	at org.acra.ErrorReporter.endApplication(ErrorReporter.java:391)
	at org.acra.ErrorReporter.access$300(ErrorReporter.java:81)
	at org.acra.ErrorReporter$4.run(ErrorReporter.java:738)

**Comment by mixonic** [comment]
@ArunkumarChandraSekar would be happy to provide guidance on this if I knew what it was.
