### ISSUE TITLE
Torii session giving weird error when the dist is run on server

### ISSUE THREAD

**Issue by v3ss0n** [Vestorly/torii#314]
Hi, not sure this is an abandoned project.

Torii is running totally fine when running using `ember serve` command. Everything , works.
But when i test to run on production server  i am having this:

```
ember.debug.js:30610 Error while processing route: login Attempting to inject an unknown injection: `service:session` Error: Attempting to inject an unknown injection: `service:session`
    at Object.validateInjections (http://localhost:9999/static/assets/vendor.js:12919:17)
    at http://localhost:9999/static/assets/vendor.js:12107:30
    at runInDebug (http://localhost:9999/static/assets/vendor.js:17447:5)
    at Object.runInDebug (http://localhost:9999/static/assets/vendor.js:30140:38)
    at instantiate (http://localhost:9999/static/assets/vendor.js:12101:24)
    at lookup (http://localhost:9999/static/assets/vendor.js:11955:17)
    at Object.lookup (http://localhost:9999/static/assets/vendor.js:11874:14)
    at Class.lookup (http://localhost:9999/static/assets/vendor.js:45149:33)
    at Class.controllerFor (http://localhost:9999/static/assets/vendor.js:39763:26)
    at Class.setup (http://localhost:9999/static/assets/vendor.js:39303:36)
```

**Comment by mixonic** [comment]
Hey @v3ss0n is this still an issue? you can provide reproduction steps or a demo repo with the problem? Definitely not a thing we've seen before.

**Comment by bantic** [comment]
Since there hasn't been much activity here for a little while I'm goign to close, but feel free to reopen when you have some more details to share. thanks!
