### ISSUE TITLE
Using torii with FastBoot

### ISSUE THREAD

**Issue by Redsandro** [Vestorly/torii#423]
I can't seem to properly run this in a FastBoot app.

Torii works fine, but once I turn my app into FastBoot, I'm getting DOM requirement errors.

> ReferenceError: document is not defined

```
There was an error running your app in fastboot. More info about the error: 
 ReferenceError: document is not defined
    at loadScript (/tmp/broccoli_merge_trees-output_path-foo.tmp/assets/addon-tree-output/torii/providers/-private/utils.js:24:1)
    at Ember.RSVP.Promise.then.window.fbAsyncInit (/tmp/broccoli_merge_trees-output_path-foo.tmp/assets/addon-tree-output/torii/providers/facebook-connect.js:34:1)
    at initializePromise (/tmp/broccoli_merge_trees-output_path-foo.tmp/assets/rsvp.js:397:1)
    at new Promise (/tmp/broccoli_merge_trees-output_path-foo.tmp/assets/rsvp.js:877:1)
    at fbLoad (/tmp/broccoli_merge_trees-output_path-foo.tmp/assets/addon-tree-output/torii/providers/facebook-connect.js:26:1)
    at Class.init (/tmp/broccoli_merge_trees-output_path-foo.tmp/assets/addon-tree-output/torii/providers/facebook-connect.js:84:1)
```

`Ember 3.5`
`Torii 0.10.1`

Is there a specific way this needs to be set up, or is the `torii` plugin simply incompatible with `FastBoot`?

**Comment by Redsandro** [comment]
> This is happening when I'm using the `facebook-connect` adapter, but `this.get('torii).open('facebook-connect')` is only fired within a user activated `action`, so I don't understand why `facebook-connect.js` is running serverside (FastBoot) at all.

@cibernox @bantic @Dhaulagiri @andorfermichael you have worked on this connector. Any ideas?

**Comment by ehubbell** [comment]
@Redsandro I got this to work on my end. You basically need to block against the `FacebookConnectProvider` not being available when the app boots in fastboot. Then, after it's loaded the FacebookConnectProvider service will go through. Not sure what's happening in the `fetch()` call but something in that call breaks the build. 

Here's what you need:

Add the following to `torii-providers/facebook-connect.js`

```
import FacebookConnectProvider from 'torii/providers/facebook-connect';
import { inject as service } from '@ember/service';
import { reads } from '@ember/object/computed';

export default FacebookConnectProvider.extend({
  	// Services
  fastboot: service(),

  
  // Properties
  isFastboot: reads('fastboot.isFastboot'),

  fetch(data) {
    if(get(this, 'isFastboot')) {
      return;
    }
    return data;
  }
});
```

Let me know any questions.

**Comment by jkeen** [comment]
Future travelers using `torii` ^0.10, you're gonna want the fix below since it now eager loads the FB connect code in the init hook. Also to save you from the pain I just experienced, the fix above has a casing typo: `isFastBoot` needs that very crucial capital B! 😅 

```javascript
import FacebookConnectProvider from 'torii/providers/facebook-connect';
import { inject as service } from '@ember/service';
import { reads } from '@ember/object/computed';
import { get } from '@ember/object';

export default FacebookConnectProvider.extend({
  fastboot: service(),
  isFastBoot: reads('fastboot.isFastBoot'),

  init() {
    if(get(this, 'isFastBoot')) {
      return;
    }
    else {
      this._super(...arguments);
    }
  },
});
```

**Comment by Redsandro** [comment]
Thanks for the tip. I keep making that mistake everywhere!

> it now eager loads the FB connect code in the init hook

Can we defer this? Eager loading any sort of social media code does not comply with GDPR.

**Comment by lionelrudaz** [comment]
@jkeen @Redsandro I've got exactly the same issue. Copied and pasted your code, no luck. I was wondering if you had any updates on this? Is there anything I can help?

**Comment by jkeen** [comment]
@lionelrudaz No idea, sorry. I ran into this on a client project that I wrapped up last year. Haven't had to deal with this since.

**Comment by ehubbell** [comment]
@lionelrudaz Torii is outdated and really doesn't work well with modern browsers. Even if you get it work, you'll run into issues with Safari and mobile browsers and pop-up blockers. Believe me, I banged my head against Torii and this issue for awhile. 

I use google and facebook connect in all my apps using either companies recommended strategy. Here's a code snippet pulled from our `facebook-btn` component:

```
didInsertElement() {
	window.fbAsyncInit = function() {
	    window.FB.init({
	      appId: config.facebook.appId,
	      cookie: false,
	      xfbml: true,
	      version: 'v6.0'
	    });
	    window.FB.AppEvents.logPageView();   
	  };

	  (function(d, s, id){
	     var js, fjs = d.getElementsByTagName(s)[0];
	     if (d.getElementById(id)) {return;}
	     js = d.createElement(s); js.id = id;
	     js.src = "https://connect.facebook.net/en_US/sdk.js";
	     fjs.parentNode.insertBefore(js, fjs);
	   }(document, 'script', 'facebook-jssdk'));
	},


	// Events
	click() {
		if(get(this, 'user.facebookId')) {
			return false;
		}
		this.facebookLogin();
		return false;
	},


	// Tasks
	facebookAuth: task(function * (data) {
		try {
			yield this.get('session').authenticate('authenticator:facebook-oauth2', data.userID, data.accessToken);
			window.mixpanel.track('Facebook login');
			yield timeout(500);
			get(this, 'flow') ? this.nextAction() : this.afterAuthAction();
		} catch(e) {
			this._serverError(e);
		}
	}).drop(),

	
	// Methods
  facebookLogin() {
  	var _this = this;
  	if(this.checkStatus() == true) {
  		_this.login();
  	} else {
  		window.FB.login(function(response) {
  			console.log('User is logged in.');
  			get(_this, 'facebookAuth').perform(response.authResponse);
  		}, { scope: 'public_profile,email' })	
  	}
  },

  checkStatus() {
		window.FB.getLoginStatus(response => {
			if (response.status === 'connected') {
				console.log("User is connected.");
        return true;
      } 
      console.log("User is not connected.");
      return false;
    });
  },

  login() {
  	window.FB.getLoginStatus(response => {
      get(this, 'facebookAuth').perform(response.authResponse);
    });
  },

  fetchUser() {
  	console.log('Welcome!  Fetching your information... ');
  	window.FB.api('/me', response => {
	  	console.log('Successful login for: ' + response.name);
  	});
  },
```

The code above gets the necessary information from Facebook in-browser and then pulls the remaining information server-side.

**Comment by lionelrudaz** [comment]
Thanks @jkeen and @ehubbell, this was really insightful. I ended up doing my own component based on your example @ehubbell.

I post the code below, it might be useful as it's with Ember Octane syntax.

```
import Component from '@glimmer/component';
import { action, get } from "@ember/object";
import { inject as service } from '@ember/service';


export default class FacebookBtnComponent extends Component {
  @service session;

  initFacebookSDK() {
    window.fbAsyncInit = function() {
      window.FB.init({
        appId: ENV.APP.facebookClientId,
        cookie: false,
        xfbml: true,
        version: 'v7.0'
      });
      window.FB.AppEvents.logPageView();
    };

    (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "https://connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  }

  checkStatus() {
		window.FB.getLoginStatus(response => {
			if (response.status === 'connected') {
				console.log("User is connected.");
        return true;
      }
      console.log("User is not connected.");
      return false;
    });
  }

  facebookLogin() {
    const _this = this;
  	if(this.checkStatus() == true) {
      console.log('User is connected to FB');
  		_this.login();
  	} else {
  		window.FB.login(function(response) {
        console.log('User is logged in.');
        console.log(response);
  			_this.facebookAuth(response.authResponse).then((data) => {
          if (_this.args.onSuccess) {
            _this.args.onSuccess();
          }
        });
  		}, { scope: 'public_profile,email' })
  	}
  }

  login() {
    console.log('Login');
  	window.FB.getLoginStatus(response => {
      this.facebookAuth(response.authResponse);
    });
  }

  facebookAuth(data) {
    try {
			return this.session.authenticate('authenticator:facebook-oauth2', data.accessToken);
		} catch(e) {
			console.log(e);
		}
  }

  @action
  loginWithFacebook() {
    if(get(this, 'user.facebookId')) {
      console.log('Facebook ID is defined, return false');
			return false;
		}
		this.facebookLogin();
		return false;
  }
}
```

I hope this helps, and good luck for the next ones. Now I need to figure out why I get a TransitionAborted error with FastBoot when my session is invalidated :)
